// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: common.proto

package API_Presidio

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// doc-false
type Error struct {
	ErrorCode            uint32            `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FieldErrors          map[string]string `protobuf:"bytes,3,rep,name=field_errors,json=fieldErrors,proto3" json:"field_errors,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetErrorCode() uint32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetFieldErrors() map[string]string {
	if m != nil {
		return m.FieldErrors
	}
	return nil
}

// doc-false
type Bytes32 struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bytes32) Reset()         { *m = Bytes32{} }
func (m *Bytes32) String() string { return proto.CompactTextString(m) }
func (*Bytes32) ProtoMessage()    {}
func (*Bytes32) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}
func (m *Bytes32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bytes32.Unmarshal(m, b)
}
func (m *Bytes32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bytes32.Marshal(b, m, deterministic)
}
func (m *Bytes32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bytes32.Merge(m, src)
}
func (m *Bytes32) XXX_Size() int {
	return xxx_messageInfo_Bytes32.Size(m)
}
func (m *Bytes32) XXX_DiscardUnknown() {
	xxx_messageInfo_Bytes32.DiscardUnknown(m)
}

var xxx_messageInfo_Bytes32 proto.InternalMessageInfo

func (m *Bytes32) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// For non-negative numbers only.
type Precise struct {
	// The full UNSIGNED number in string form. max value is 2^257 - 1,
	// aka 231584178474632390847141970017375815706539969331281128078915168015826259279871
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Precise) Reset()         { *m = Precise{} }
func (m *Precise) String() string { return proto.CompactTextString(m) }
func (*Precise) ProtoMessage()    {}
func (*Precise) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}
func (m *Precise) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Precise.Unmarshal(m, b)
}
func (m *Precise) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Precise.Marshal(b, m, deterministic)
}
func (m *Precise) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Precise.Merge(m, src)
}
func (m *Precise) XXX_Size() int {
	return xxx_messageInfo_Precise.Size(m)
}
func (m *Precise) XXX_DiscardUnknown() {
	xxx_messageInfo_Precise.DiscardUnknown(m)
}

var xxx_messageInfo_Precise proto.InternalMessageInfo

func (m *Precise) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// doc-false
type SignedPrecise struct {
	// The full SIGNED number in string form.
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedPrecise) Reset()         { *m = SignedPrecise{} }
func (m *SignedPrecise) String() string { return proto.CompactTextString(m) }
func (*SignedPrecise) ProtoMessage()    {}
func (*SignedPrecise) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}
func (m *SignedPrecise) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedPrecise.Unmarshal(m, b)
}
func (m *SignedPrecise) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedPrecise.Marshal(b, m, deterministic)
}
func (m *SignedPrecise) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedPrecise.Merge(m, src)
}
func (m *SignedPrecise) XXX_Size() int {
	return xxx_messageInfo_SignedPrecise.Size(m)
}
func (m *SignedPrecise) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedPrecise.DiscardUnknown(m)
}

var xxx_messageInfo_SignedPrecise proto.InternalMessageInfo

func (m *SignedPrecise) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// doc-false
type CurrencyAmount struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Amount               *Precise `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrencyAmount) Reset()         { *m = CurrencyAmount{} }
func (m *CurrencyAmount) String() string { return proto.CompactTextString(m) }
func (*CurrencyAmount) ProtoMessage()    {}
func (*CurrencyAmount) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}
func (m *CurrencyAmount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrencyAmount.Unmarshal(m, b)
}
func (m *CurrencyAmount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrencyAmount.Marshal(b, m, deterministic)
}
func (m *CurrencyAmount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrencyAmount.Merge(m, src)
}
func (m *CurrencyAmount) XXX_Size() int {
	return xxx_messageInfo_CurrencyAmount.Size(m)
}
func (m *CurrencyAmount) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrencyAmount.DiscardUnknown(m)
}

var xxx_messageInfo_CurrencyAmount proto.InternalMessageInfo

func (m *CurrencyAmount) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *CurrencyAmount) GetAmount() *Precise {
	if m != nil {
		return m.Amount
	}
	return nil
}

// Used for paginating results.
type PaginationSummary struct {
	// The current page number
	PageNumber uint32 `protobuf:"varint,1,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	// The number of entries to show per page.
	PageSize uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// The number of items matching the request across all pages.
	TotalEntries uint32 `protobuf:"varint,3,opt,name=total_entries,json=totalEntries,proto3" json:"total_entries,omitempty"`
	// The number of pages need to show total_entries at the given page_size.
	TotalPages           uint32   `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaginationSummary) Reset()         { *m = PaginationSummary{} }
func (m *PaginationSummary) String() string { return proto.CompactTextString(m) }
func (*PaginationSummary) ProtoMessage()    {}
func (*PaginationSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{5}
}
func (m *PaginationSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginationSummary.Unmarshal(m, b)
}
func (m *PaginationSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginationSummary.Marshal(b, m, deterministic)
}
func (m *PaginationSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginationSummary.Merge(m, src)
}
func (m *PaginationSummary) XXX_Size() int {
	return xxx_messageInfo_PaginationSummary.Size(m)
}
func (m *PaginationSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginationSummary.DiscardUnknown(m)
}

var xxx_messageInfo_PaginationSummary proto.InternalMessageInfo

func (m *PaginationSummary) GetPageNumber() uint32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *PaginationSummary) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PaginationSummary) GetTotalEntries() uint32 {
	if m != nil {
		return m.TotalEntries
	}
	return 0
}

func (m *PaginationSummary) GetTotalPages() uint32 {
	if m != nil {
		return m.TotalPages
	}
	return 0
}

func init() {
	proto.RegisterType((*Error)(nil), "API.Presidio.Error")
	proto.RegisterMapType((map[string]string)(nil), "API.Presidio.Error.FieldErrorsEntry")
	proto.RegisterType((*Bytes32)(nil), "API.Presidio.Bytes32")
	proto.RegisterType((*Precise)(nil), "API.Presidio.Precise")
	proto.RegisterType((*SignedPrecise)(nil), "API.Presidio.SignedPrecise")
	proto.RegisterType((*CurrencyAmount)(nil), "API.Presidio.CurrencyAmount")
	proto.RegisterType((*PaginationSummary)(nil), "API.Presidio.PaginationSummary")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x8b, 0xd3, 0x40,
	0x14, 0xc7, 0xc9, 0xd6, 0xed, 0x9a, 0x97, 0x44, 0x77, 0x07, 0x95, 0xa0, 0xc8, 0x96, 0xa8, 0xd0,
	0x8b, 0x39, 0x64, 0x2f, 0xe2, 0x41, 0xa8, 0xb5, 0x8a, 0x17, 0x09, 0x89, 0xe0, 0x31, 0x4c, 0x93,
	0xd7, 0x38, 0x98, 0x99, 0x29, 0x33, 0x13, 0x21, 0xfd, 0x22, 0x7e, 0x26, 0xbf, 0x95, 0xcc, 0x24,
	0xa5, 0xd6, 0x83, 0xb7, 0xf7, 0x7e, 0xfc, 0x26, 0xff, 0xc7, 0x7b, 0x81, 0xb0, 0x96, 0x9c, 0x4b,
	0x91, 0xee, 0x95, 0x34, 0x92, 0x84, 0xab, 0xfc, 0x73, 0x9a, 0x2b, 0xd4, 0xac, 0x61, 0x32, 0xf9,
	0xed, 0xc1, 0xe5, 0x46, 0x29, 0xa9, 0xc8, 0x73, 0x00, 0xb4, 0x45, 0x55, 0xcb, 0x06, 0x63, 0x6f,
	0xe1, 0x2d, 0xa3, 0xc2, 0x77, 0x64, 0x2d, 0x1b, 0x24, 0x31, 0x5c, 0x71, 0xd4, 0x9a, 0xb6, 0x18,
	0x5f, 0x2c, 0xbc, 0xa5, 0x5f, 0x1c, 0x5b, 0xf2, 0x09, 0xc2, 0x1d, 0xc3, 0xae, 0xa9, 0x9c, 0xac,
	0xe3, 0xd9, 0x62, 0xb6, 0x0c, 0xb2, 0x97, 0xe9, 0xdf, 0x39, 0xa9, 0xcb, 0x48, 0x3f, 0x5a, 0xcf,
	0x95, 0x7a, 0x23, 0x8c, 0x1a, 0x8a, 0x60, 0x77, 0x22, 0x4f, 0xdf, 0xc1, 0xf5, 0xbf, 0x02, 0xb9,
	0x86, 0xd9, 0x0f, 0x1c, 0xdc, 0x38, 0x7e, 0x61, 0x4b, 0xf2, 0x08, 0x2e, 0x7f, 0xd2, 0xae, 0x3f,
	0x8e, 0x31, 0x36, 0x6f, 0x2f, 0xde, 0x78, 0xc9, 0x2d, 0x5c, 0xbd, 0x1f, 0x0c, 0xea, 0xbb, 0xec,
	0x24, 0xd9, 0x87, 0xe1, 0x24, 0x59, 0x21, 0x57, 0x58, 0x33, 0x8d, 0xe7, 0xc2, 0xf1, 0x2b, 0xc9,
	0x2b, 0x88, 0x4a, 0xd6, 0x0a, 0x6c, 0xfe, 0xaf, 0x7d, 0x83, 0x07, 0xeb, 0x5e, 0x29, 0x14, 0xf5,
	0xb0, 0xe2, 0xb2, 0x17, 0x86, 0x3c, 0x81, 0xb9, 0x1e, 0xf8, 0x56, 0x76, 0x93, 0x38, 0x75, 0xe4,
	0x35, 0xcc, 0xa9, 0x33, 0xdc, 0xb4, 0x41, 0xf6, 0xf8, 0x7c, 0x2b, 0x53, 0x4c, 0x31, 0x49, 0xc9,
	0x2f, 0x0f, 0x6e, 0x72, 0xda, 0x32, 0x41, 0x0d, 0x93, 0xa2, 0xec, 0x39, 0xa7, 0x6a, 0x20, 0xb7,
	0x10, 0xec, 0x69, 0x8b, 0x95, 0xe8, 0xf9, 0x16, 0xd5, 0x74, 0x1a, 0xb0, 0xe8, 0x8b, 0x23, 0xe4,
	0x19, 0xf8, 0x4e, 0xd0, 0xec, 0x30, 0xae, 0x25, 0x2a, 0xee, 0x5b, 0x50, 0xb2, 0x03, 0x92, 0x17,
	0x10, 0x19, 0x69, 0x68, 0x57, 0xa1, 0x30, 0x8a, 0xa1, 0xbd, 0x8f, 0x15, 0x42, 0x07, 0x37, 0x23,
	0xb3, 0x11, 0xa3, 0x64, 0x9f, 0xe9, 0xf8, 0xde, 0x18, 0xe1, 0x50, 0x6e, 0x49, 0x76, 0x03, 0x0f,
	0xcb, 0xef, 0x54, 0x61, 0xf3, 0x81, 0x1a, 0xfa, 0x75, 0xd8, 0xa3, 0xde, 0xce, 0xdd, 0xff, 0x74,
	0xf7, 0x27, 0x00, 0x00, 0xff, 0xff, 0x54, 0x44, 0xdd, 0x12, 0x5f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SharedDataTypesClient is the client API for SharedDataTypes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SharedDataTypesClient interface {
}

type sharedDataTypesClient struct {
	cc *grpc.ClientConn
}

func NewSharedDataTypesClient(cc *grpc.ClientConn) SharedDataTypesClient {
	return &sharedDataTypesClient{cc}
}

// SharedDataTypesServer is the server API for SharedDataTypes service.
type SharedDataTypesServer interface {
}

func RegisterSharedDataTypesServer(s *grpc.Server, srv SharedDataTypesServer) {
	s.RegisterService(&_SharedDataTypes_serviceDesc, srv)
}

var _SharedDataTypes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "API.Presidio.SharedDataTypes",
	HandlerType: (*SharedDataTypesServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "common.proto",
}
